import { IncidentScenario } from './mock-incidents';

export function generatePrintableHTML(incident: IncidentScenario): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>WINDCOVER AI - Executive Crisis Intelligence & Recovery Report</title>
  <style>
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      color: #111;
      line-height: 1.6;
      margin: 40px;
      background: #fff;
    }
    .header {
      border-bottom: 3px solid #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .title {
      font-size: 28px;
      font-weight: 900;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin: 0;
    }
    .subtitle {
      font-size: 14px;
      color: #666;
      margin-top: 5px;
    }
    .badge {
      display: inline-block;
      padding: 6px 12px;
      background: #000;
      color: #fff;
      font-weight: bold;
      border-radius: 4px;
      font-size: 12px;
      text-transform: uppercase;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin-bottom: 30px;
    }
    .card {
      border: 1px solid #ddd;
      padding: 15px;
      border-radius: 6px;
      background: #fdfdfd;
    }
    .card-title {
      font-size: 12px;
      text-transform: uppercase;
      color: #777;
      font-weight: bold;
      margin-bottom: 8px;
    }
    .card-value {
      font-size: 20px;
      font-weight: bold;
    }
    h2 {
      font-size: 18px;
      border-bottom: 1px solid #ccc;
      padding-bottom: 8px;
      margin-top: 35px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    ul, ol {
      padding-left: 20px;
    }
    li {
      margin-bottom: 8px;
    }
    .footer {
      margin-top: 50px;
      border-top: 1px solid #ddd;
      padding-top: 15px;
      font-size: 11px;
      color: #888;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">WINDCOVER AI</h1>
      <div class="subtitle">AI-Powered Crisis Intelligence & Recovery Platform</div>
    </div>
    <div>
      <span class="badge">SEVERITY: ${incident.severity} (${incident.severityScore}/100)</span>
    </div>
  </div>

  <div style="margin-bottom: 30px;">
    <h3 style="margin-bottom: 5px;">${incident.title}</h3>
    <p style="color: #444;">${incident.description}</p>
  </div>

  <div class="grid">
    <div class="card">
      <div class="card-title">Estimated Financial Impact</div>
      <div class="card-value">${incident.metrics.financialImpact}</div>
    </div>
    <div class="card">
      <div class="card-title">Systems Affected</div>
      <div class="card-value">${incident.metrics.systemsAffected} Core Endpoints</div>
    </div>
    <div class="card">
      <div class="card-title">Blast Radius / People Affected</div>
      <div class="card-value">${incident.metrics.peopleAffected}</div>
    </div>
    <div class="card">
      <div class="card-title">Prediction Confidence</div>
      <div class="card-value">${incident.metrics.predictionConfidence}%</div>
    </div>
  </div>

  <h2>1. Executive Summary</h2>
  <p>${incident.executiveSummary}</p>

  <h2>2. Chronological Timeline</h2>
  <ul>
    ${incident.timeline.map(t => `<li><strong>[${t.time}]</strong> ${t.event} <em>(${t.source})</em></li>`).join('')}
  </ul>

  <h2>3. Root Cause Decomposition</h2>
  <ul>
    ${incident.rootCauses.map(rc => `<li><strong>${rc.factor}</strong> (${rc.impact}): ${rc.detail}</li>`).join('')}
  </ul>

  <h2>4. 24-Hour Immediate Action Plan</h2>
  <ol>
    ${incident.actionPlan24h.map(act => `<li>${act}</li>`).join('')}
  </ol>

  <h2>5. 7-Day Hardening & Recovery Plan</h2>
  <ol>
    ${incident.recoveryPlan7d.map(rec => `<li>${rec}</li>`).join('')}
  </ol>

  <h2>6. Future Risk Predictions</h2>
  <ul>
    ${incident.futurePredictions.map(p => `<li><strong>[${p.timeframe}] ${p.event}</strong> - Probability: ${p.probability}% (Risk: ${p.riskLevel})</li>`).join('')}
  </ul>

  <div class="footer">
    Generated by WindCover AI Mission Control Engine • Autonomous ASI:ONE Orchestration Architecture Prototype • Confidential Telemetry
  </div>

  <script>
    window.onload = function() {
      // Optional auto-trigger print for PDF export
    }
  </script>
</body>
</html>
  `;
}
